socialnet/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import *
from django.conf import settings # !
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage),
    path('posts/<int:id>/', post_detail, name='post-detail'),
    path('post-cbv/<int:id>/', PostDetailView.as_view(), name='post-detail-cbv'),
    path('posts-list-cbv/', PostListView.as_view(), name='posts-list-cbv'),
    path('posts-api/', PostsFromAPI.as_view(), name='posts-api'),
    path('posts-api/<int:id>/', PostDetailFromAPI.as_view(), name='post-api'),
    path('profile/<int:id>/', profile_detail, name='profile'),
    path('add-profile/', add_profile, name='add-profile'),
    path('shorts/', shorts, name='shorts-list'),
    path('shorts-cbv/', ShortsListView.as_view(), name='shorts-cbv'),
    path('shorts-filter/', ShortsFilterView.as_view(), name='shorts-filter'),
    path('short/<int:id>/', short_info, name='shorts-info'),
    path('short-cbv/<int:pk>/', ShortDetailView.as_view(), name='short-cbv'),
    path('add-short/', add_short, name='add-short'),
    path('update-short/<int:id>/', update_short, name='update-short'),
    path('saved_posts/', saved_posts_list, name='saved-posts'),
    path('<int:user_id>/', user_posts, name='user-posts'),
    path('add-post/', create_post, name='add-post'),
    path('update-post/<int:id>/', update_post, name='update-post'),
    path('delete-post/<int:id>/', detele_post, name='delete-post'),
    path('add-post-form/', add_post_form, name='add-post-form'),
    path('add-saved/', add_saved, name='add-saved'),
    # path('search/', search, name='search'),
    # path('search-result/', search_result, name='search-result'),
    path('search/', SearchView.as_view(), name='search'),
    path('search-result/', SearchResultView.as_view(), name='search-result'),
    path('subscribes/<int:user_id>/', SubscribesView.as_view(), name='subscribes'),
    path('subscribe/<int:profile_id>/', subscribe, name='subscribe'),
    path('unsubscribe/<int:profile_id>/', unsubscribe, name='unsubscribe'),
    path('notifications/', notifications, name='notifications'),
    path('notifications-cbv/', NotificationView.as_view(), name='notifications-cbv'),
    path('comment-edit/<int:id>/', comment_edit, name='comment-edit'),
    path('comment-delete/<int:id>/', comment_delete, name='comment-delete'),
    path('about/', AboutView.as_view(), name='about'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('faq/', QuestionsView.as_view(), name='faq'),
    path('users/', include('userapp.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userapp/urls.py
from django.urls import path
from .views import *
# from .views import sign_in
# from . import views
# from userapp.views import


urlpatterns = [
    # /users/registration/
    path('registration/', registration, name='registration'),

    # /users/sign-in/
    path('sign-in/', sign_in, name='sign-in'),
    path('sign-out/', sign_out, name='sign-out'),
    
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(
        to=User,
        on_delete=models.CASCADE
    )
    nickname = models.CharField(max_length=55)
    description = models.TextField(null=True, blank=True)
    subscribers = models.ManyToManyField(
        to=User,
        related_name='followed_profile',
        blank=True,
    )
    photo = models.ImageField(
        upload_to='profile_photo/',
        null=True
    )
    link_fb = models.CharField(
        max_length=255, null=True, blank=True
    )
    whatsapp = models.CharField(
        max_length=30, null=True, blank=True
    )
    telegram = models.CharField(
        max_length=55, null=True, blank=True
    )
    

class Post(models.Model):
    STATUS_CHOICES = (
        ('Posted', 'Posted'),
        ('Unposted', 'Unposted')
    )

    name = models.CharField('Header', max_length=80, null=True, blank=True)
    description = models.TextField('Description', null=True, blank=True)
    photo = models.ImageField('Photo', null=True, blank=False, upload_to="post_images/")
    status = models.CharField(
        'Status',
        max_length=200,
        choices=STATUS_CHOICES,
        default="Posted"
    )
    # M2O
    creator = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        null=True,  # необязательно в БД
        blank=False,  # обязательно в Django
        verbose_name="Автор поста",
        related_name="posts"  # default == post_set
    )

    category = models.ManyToManyField(
        to='Category',
        blank=True,
        verbose_name='Категории',
    )
    likes = models.IntegerField('Лайк', default=0)

    def __str__(self):
        return f'{self.name} - {self.status}'

    class Meta:
        ordering = ['id']

class Category(models.Model):
    RATING_CHOICES = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10)
    )

    name = models.CharField(max_length=50)
    rating = models.PositiveSmallIntegerField(
        choices=RATING_CHOICES,
        null=True,
        blank=True,
    )

    def __str__(self):
        return f'{self.name} - {self.rating}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Comment(models.Model):
    post = models.ForeignKey(
        to=Post,
        on_delete=models.CASCADE
    )
    comment_text = models.TextField()
    likes_qty = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        null=True, blank=False
    )

    def __str__(self):
        return self.comment_text[:20]
    
    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['created_at']


class Short(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        verbose_name='Автор',
        related_name='short'
    )
    video = models.FileField('Видео', upload_to='video_post/')
    created_at = models.DateTimeField(auto_now_add=True)
    views_qty = models.PositiveIntegerField('Просмотры', default=0)
    viewed_users = models.ManyToManyField(
        to=User,
        blank=True,
        related_name='viewed_shorts'
    )
    description = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = 'Видео'
        verbose_name_plural = 'Видео'

    def __str__(self):
        return f'{self.video} - {self.created_at}'


class SavedPosts(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    post = models.ManyToManyField(Post, verbose_name='saved post', related_name='saved_posts')

    class Meta:
        verbose_name = 'saved post'
        verbose_name_plural = 'saved posts'

    def __str__(self):
        return f'{self.user}'


class Notification(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.PROTECT)
    text = models.CharField(max_length=255)
    is_showed = models.BooleanField(default=False)

    def __str__(self):
        return self.text

core/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.views import View
from django.views.generic import ListView, DetailView
from django_filters.views import FilterView
import requests
from .models import *
from .forms import *
from .filters import *


class NoContextView(View):
    template_name = None # required

    def get(self, request):
        return render(request, self.template_name)

class AboutView(NoContextView):
    template_name = 'core/about.html'

class ContactsView(NoContextView):
    template_name = 'contacts.html'

class QuestionsView(NoContextView):
    template_name = 'faq.html'

# class AboutView(View):
#     def get(self, request):
#         return render(request, 'about.html')

# Create your views here.
def homepage(request):
    context = {}
    posts_list = Post.objects.all() # SELECT * FROM Post;
    context["posts"] = posts_list

    shorts_list = Short.objects.all()
    context["shorts"] = shorts_list

    return render(request, "home.html", context)


def post_detail(request, id):
    context = {}
    post_object = Post.objects.get(id=id)
    context["post"] = post_object
    comment_form = CommentForm()
    context["comment_form"] = comment_form
    comments_list = Comment.objects.filter(post=post_object)
    context['comments'] = comments_list
    # от начала до сюда

    if request.method == "GET":
        return render(request, "post_info.html", context)
    elif request.method == "POST":
        # от сюда до конца
        if 'like' in request.POST:
            post_object.likes += 1
            post_object.save()
            Notification.objects.create(
                user=post_object.creator,
                text=f"{request.user.username} лайкнул ваш пост с id {post_object.id} "
            )
            return redirect(post_detail, id=id)
        else:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.created_by = request.user
                new_comment.post = post_object
                new_comment.save()

                Notification.objects.create(
                    user=post_object.creator,
                    text=f"{request.user.username} оставил комментарий"
                )
                return HttpResponse("done")


class PostDetailView(View):
    def get_context(self):
        id = self.kwargs["id"]
        context = {}
        post_object = Post.objects.get(id=id)
        context["post"] = post_object
        comment_form = CommentForm()
        context["comment_form"] = comment_form
        comments_list = Comment.objects.filter(post=post_object)
        context['comments'] = comments_list
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context()
        return render(request, "post_info.html", context) 
    
    def post(self, request, *args, **kwargs):
        context = self.get_context()
        post_object = context["post"]
        if 'like' in request.POST:
            post_object.likes += 1
            post_object.save()
            Notification.objects.create(
                user=post_object.creator,
                text=f"{request.user.username} лайкнул ваш пост с id {post_object.id} "
            )
        else:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.created_by = request.user
                new_comment.post = post_object
                new_comment.save()

                Notification.objects.create(
                    user=post_object.creator,
                    text=f"{request.user.username} оставил комментарий"
                )
        return redirect('post-detail-cbv', id=post_object.id)


class PostListView(ListView):
    queryset = Post.objects.all()
    # template_name = 'core/post_list.html'


class PostsFromAPI(View):
    def get(self, request):
        context = {}
        response = requests.get("https://jsonplaceholder.typicode.com/posts")
        data = response.json()
        context["posts"] = data
        return render(request, 'core/posts_from_api.html', context)

class PostDetailFromAPI(View):
    def get(self, request, *args, **kwargs):
        id = kwargs['id']
        response = requests.get(f'https://jsonplaceholder.typicode.com/posts/{id}')
        post_data = response.json()
        return render(request, 'core/post_from_api.html', {'post': post_data})


def profile_detail(request, id):
    context = {}
    profile = Profile.objects.get(id=id)
    context['profile'] = profile

    if request.method == "POST":
        profile.subscribers.add(request.user)
        profile.save()
    
    return render(request, 'profile_detail.html', context)


def add_profile(request):
    profile_form = ProfileForm()
    context = {'profile_form': profile_form}

    if request.method == "POST":
        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            profile_object = profile_form.save(commit=False)
            profile_object.user = request.user
            profile_object.save()
            return redirect(profile_detail, id=profile_object.id)
        else:
            return HttpResponse("Not valid")

    return render(request, 'add_profile.html', context)


def shorts(request):
    short_filter = ShortFilter(
        request.GET,
        queryset=Short.objects.all()
    )
    context = {'short_filter': short_filter}
    return render(request, "shorts.html", context)

class ShortsListView(ListView):
    queryset = Short.objects.all()

class ShortsFilterView(FilterView):
    model = Short
    filterset_class = ShortFilter
    # template_name = 'app/model_filter.html'
    # template_name = 'core/short_filter.html'
    # filterset_fields = ['id', 'user', 'views_qty']


def short_info(request, id):
    try:
        short = Short.objects.get(id=id)
    except Short.DoesNotExist:
        return HttpResponse(
            "Ошибка 404. Такого объекта не существует"
        )
    short.views_qty += 1
    if request.user.is_authenticated:
        short.viewed_users.add(request.user)
    short.save()
    context = {"short": short}
    return render(request, "short_info.html", context)


class ShortDetailView(DetailView):
    queryset = Short.objects.all()
    template_name = "short_info.html"

    def get(self, request, *args, **kwargs):
        short = self.get_object()
        short.views_qty += 1
        if request.user.is_authenticated:
            short.viewed_users.add(request.user)
        short.save()
        return super().get(request, *args, **kwargs)
    

def saved_posts_list(request):
    posts = Post.objects.filter(saved_posts__user=request.user)
    context = {'posts': posts}
    return render(request, 'saved_posts.html', context)


def user_posts(request, user_id):
    user = User.objects.get(id=user_id)
    posts = Post.objects.filter(creator=user)
    context = {
        "user": user,
        "posts": posts
    }
    return render(request, 'user_posts.html', context)


def create_post(request):
    if request.method == "GET":
        return render(request, "create_post_form.html")
    elif request.method == "POST":
        data = request.POST  # словарь с данными с html-формы
        # print(data)
        new_post = Post()
        new_post.name = data["post_name"]
        new_post.description = data["description"]
        new_post.photo = request.FILES["photo"]
        new_post.creator = request.user
        new_post.save()
        return HttpResponse("done")


def update_post(request, id):

    context = {}
    post_object = Post.objects.get(id=id)

    if request.user != post_object.creator:
        return HttpResponse("нет доступа")

    if request.method == "POST":
        post_form = PostForm(
            data=request.POST,
            files=request.FILES,
            instance=post_object
        )
        if post_form.is_valid():
            post_form.save()
            return redirect(post_detail, id=post_object.id)
        else:
            messages.warning(request, "Форма не валидна")
            context["post_form"] = post_form
            return render(request, 'update_post.html', context)

    post_form = PostForm(instance=post_object)
    context["post_form"] = post_form
    return render(request, 'update_post.html', context)


def detele_post(request, id):
    post = Post.objects.get(id=id)

    if request.user != post.creator:
        return HttpResponse("нет доступа")

    post.delete()
    return redirect(homepage)


def add_post_form(request):
    if request.method == "POST":
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            post_object = post_form.save(commit=False)
            post_object.creator = request.user
            post_object.save()
            return redirect(post_detail, id=post_object.id)
        else:
            messages.warning(request, f"Форма не валидна: {post_form.errors}")

    post_form = PostForm()
    context = {}
    context["post_form"] = post_form
    return render(request, 'create_post_django_form.html', context)


# from django.contrib.auth.decorators import login_required
@login_required(login_url='/users/sign-in/')
def add_short(request):
    # if not request.user.is_authenticated:
    #     return redirect('/')

    if request.method == "GET":
        return render(request, 'short_form.html')
    elif request.method == "POST":
        new_short_object = Short(
            user=request.user,
            video=request.FILES["video_file"]
        )
        new_short_object.save()
        return redirect('shorts-info', id=new_short_object.id)


def update_short(request, id):
    short = Short.objects.get(id=id)

core/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load django_bootstrap5 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Social НЭТ</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link
        rel="stylesheet"
        href="{% static 'main.css' %}"
    >
</head>
<body>
    <div class="row">
        <div class="col-3">
            <a class="navbar-brand" href="/">
              <img src="{% static 'logo.png' %}" height="40px">
              Social NET
            </a>
            <div>
              {% if request.user.is_authenticated %}
                Привет, {{ request.user.username }}!
              {% else %}
                Пожалуйста, авторизуйтесь
              {% endif %}
            </div>
            <div class="my-focus">
              <a href="/">
                Главная
              </a> 
            </div>
            <div class="my-focus">
              <a href="{% url 'about' %}">
                О нас
              </a> 
            </div>
            <div class="my-focus">
              <a href="{% url 'faq' %}">
                FAQ
              </a> 
            </div>
            <div class="my-focus">
              <a href="{% url 'contacts' %}">
                Контакты
              </a> 
            </div>
            <div class="my-focus">
              <a href="{% url 'posts-list-cbv' %}">
                Посты
              </a> 
            </div>
            <div class="my-focus">
              <a href="{% url 'posts-api' %}">
                Сторонние Посты
              </a> 
            </div>
            <div class="my-focus">
              <a href="{% url 'search' %}">
                Поисковый запрос
              </a>
            </div>
            <div class="my-focus">Интересное</div>
            <div class="my-focus">
              <a href="{% url 'shorts-list' %}">
                Shorts
              </a>
            </div>
            <div class="my-focus">
              <a href="{% url 'shorts-cbv' %}">
                Shorts-CBV
              </a>
            </div>
            <div class="my-focus">
              <a href="{% url 'shorts-filter' %}">
                Shorts-Filter
              </a>
            </div>
          {% if request.user.is_authenticated %}
            <div class="my-focus">Сообщения</div>
            <div class="my-focus">
              <a href="{% url 'notifications-cbv' %}">
                Уведомления - 
                {{ request.user.notification_set.count }}
              </a>
            </div>
            <div class="my-focus">
              <a href="{% url 'add-post' %}">
                Добавить пост
              </a>
            </div>
            <div class="my-focus">
              <a href="{% url 'add-post-form' %}">
                Добавить пост (django-form)
              </a>
            </div>
            <div class="my-focus">
              <a href="{% url 'add-short' %}">
                Добавить short
              </a>
            </div>
            {% if request.user.profile %}
              <div class="my-focus">
                <a href="{% url 'profile' request.user.profile.id %}">
                  Профиль
                </a>
              </div>
            {% else %}
              <div class="my-focus">
                <a href="{% url 'add-profile' %}">
                  Добавить профиль
                </a>
              </div>
            {% endif %}
            <div class="my-focus">
              <a href="{% url 'sign-out' %}">Выход</a>
            </div>
          {% else %}
            <div class="my-focus">
              <a href="{% url 'registration' %}">Регистрация</a>
            </div>
            <div class="my-focus">
              <a href="{% url 'sign-in' %}">Вход</a>
            </div>
          {% endif %}
        </div>
        <div class="col-9">
          {% if messages %}
            <div class="messages">
                {% for message in messages %}
                  <div 
                    {% if message.tags %}
                      class="alert alert-{{ message.tags }}"
                    {% endif %}
                  >
                    {{ message }}
                  </div>
                {% endfor %}
            </div>
          {% endif %}
          {% block content %}
            <h1>hello world</h1>
          {% endblock %}
        </div>
    </div>
    
    
</body>
</html>

core/templates/comment_edit.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary">
            Обновить
        </button>
    </form>

{% endblock %}

core/templates/contacts.html
{% extends 'base.html' %}

{% block content %}
    <h2>Контакты</h2>
    <div>whatsapp: +238753847534</div>
    <div>telegram: @socialnet</div>
    <div>email: socialnet@gmail.com</div>
{% endblock %}

core/templates/create_post_django_form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form post_form %}
            <button class="btn btn-warning">
                Добавить пост
            </button>
        </form>
    </div>

{% endblock %}

core/templates/create_post_form.html
{% extends 'base.html' %}

{% block content %}
    <h2>Добавление поста</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>
            <input class="form-control" type="text" name="post_name">
        </p>
        <p>
            <textarea class="form-control" name="description" cols="20" rows="5"></textarea>
        </p>
        <p>
            <input class="form-control" type="file" name="photo">
        </p>
        <button class="btn btn-warning">Сохранить</button>
    </form>
{% endblock %}

core/templates/faq.html
{% extends 'base.html' %}

{% block content %}
    <h2>ЧаВо</h2>
    <hr>
    <div>Как пройти регистрацию?</div>
    <div>Зайдите во вкладку "Регистрация" и заполните форму.</div>
    <hr>
    <div>Сколько будет 2 + 2?</div>
    <div>4</div>
    <hr>

{% endblock %}

core/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        {% for short in shorts %}
            <div class="col">
                <a href="{% url 'shorts-info' short.id %}">
                    <div>
                        <video
                            class="custom-circle"
                            width="100px"
                            src="{{ short.video.url }}">
                        </video>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
    <hr>

    {% include 'includes/search_form.html' %}
    <h2>Посты</h2>
    {% for post in posts %}
        <div>
            <a href="{% url 'user-posts' post.creator.id %}">
                {{ post.creator.username }}
            </a>
        </div>
        <div>
            {% if post.photo %}
                <a href="{% url 'post-detail' post.id %}">
                    <img src="{{ post.photo.url }}" height="200px">
                </a>
            {% endif %}
        </div>
        <hr>
    {% endfor %}   

{% endblock %}

core/templates/notifications.html
{% extends 'base.html' %}

{% block content %}
    <h3>Ваши уведомления</h3>
    {% for notification in notifications %}
        <hr>
        <div>
            {{ notification.text }}
        </div>
    {% endfor %}
{% endblock %}

core/templates/post_info.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}


{% block content %}

<h2>Пост</h2>
{% if post.creator %}
    <div>
        Автор:
        <a href="{% url 'user-posts' post.creator.id %}">
            {{ post.creator.username }}
        </a>
    </div>
{% endif %}
<div>
    Заголовок: {{ post.name }}
</div>
    {% if post.photo %}
        <img src="{{ post.photo.url }}" height="200px">
    {% endif %}
<div>
    Описание: {{ post.description }}
</div>
<div>
    Кол-во лайков: {{ post.likes }}
</div>
<div>
    <form method="POST">
        {% csrf_token %}
        <button name="like">Like</button>
    </form>
</div>
<p>
    {% if post in request.user.savedposts.post.all %}
        <div class="btn btn-info">Уже в сохраннённом</div>
    {% else %}
        <form action="/add-saved/" method="POST">
            {% csrf_token %}
            <input type="number" name="post_id" value="{{ post.id }}" hidden>
            <button class="btn btn-success">Добавить в Сохранённое</button>
        </form>
    {% endif %}
</p>
{% if request.user == post.creator %}
    <p>
        <a class="btn btn-success" href="{% url 'update-post' post.id %}">Изменить</a>
    </p>
    <p>
        <a class="btn btn-danger" href="{% url 'delete-post' post.id %}">Удалить</a>
    </p>
{% endif %}
<h3>Добавить комментарий</h3>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    <button class="btn btn-info">Добавить</button>
</form>
<h4>Комментарии</h4>
{% for comment in comments %}
    <div>
        <b>{{ comment.created_by }}</b>
        {{ comment.comment_text }}

        {% if request.user == comment.created_by %}
            <a href="{% url 'comment-edit' comment.id %}">
                Изменить
            </a>
            <a href="{% url 'comment-delete' comment.id %}">
                Удалить
            </a>
        {% endif %}
    </div>
{% endfor %}

{% endblock %}

core/templates/saved_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        {% for post in posts %}
            <div>
                <a href="/posts/{{ post.id }}">
                    {{ post.name }}
                </a>
            </div>
        {% endfor %}
    </div>
</body>
</html>

core/templates/search.html
{% extends 'base.html' %}
{% block content %}
    {% include 'includes/search_form.html' %}
{% endblock %}

core/templates/subscribers.html
{% extends 'base.html' %}

{% block content %}
    {% for profile in profiles_list %}
        <div>{{ profile.user.username }}</div>
    {% endfor %}
{% endblock %}

core/templates/update_post.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form post_form %}
        <button>Обновить</button>
    </form>

{% endblock %}

core/templates/user_posts.html
{% extends 'base.html' %}

{% block content %}
    <h2>Посты пользователя:
        <a href="{% url 'profile' user.profile.id %}">
            {{ user.username }}
        </a>
    </h2>
    <div class="row container">
        {% for post in posts %}
            <div class="post col-lg-4 col-md-6">
                <a href="/posts/{{ post.id }}">
                    {{ post.name }}
                </a>
                {% if post.photo %}
                    <div>
                        <a href="/posts/{{ post.id }}">
                            <img src="{{ post.photo.url }}">
                        </a>
                    </div>
                {% endif %}
                <p>
                    Лайки: {{ post.likes }}
                </p>
                <!-- <hr> прямая линия -->
            </div>

        {% endfor %}
    </div>
{% endblock %}